config/routes.rb
Rails.application.routes.draw do

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

  get '/map' => 'checkins#index'

  root 'checkins#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  resources :users

  resources :checkins

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@checkins) do |checkin, marker|
      marker.lat checkin.latitude
      marker.lng checkin.longitude
      marker.infowindow render_to_string(partial: "/maps/map_box", locals: { checkin: checkin })
    end
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)
    if @checkin.save
      redirect_to map_path, notice: 'Checkin was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    if @checkin.update(checkin_params)
      redirect_to @checkin, notice: 'Checkin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to checkins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:name, :address, :user_id, :description)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @checkins = Checkin.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@checkins) do |checkin, marker|
      marker.lat checkin.latitude
      marker.lng checkin.longitude
      marker.infowindow render_to_string(partial: "/maps/map_box", locals: { checkin: checkin })
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Cowork Fargo!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Cowork Fargo"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/checkins_helper.rb
module CheckinsHelper

  def static_map_for(checkin, options = {})
    params = {
      :center => [checkin.latitude, checkin.longitude].join(","),
      :zoom => 15,
      :size => "500x500",
      :markers => [checkin.latitude, checkin.longitude].join(","),
      :sensor => true
      }.merge(options)

    query_string =  params.map{|k,v| "#{k}=#{v}"}.join("&")
    image_tag "http://maps.googleapis.com/maps/api/staticmap?#{query_string}", :alt => checkin.name
  end

end

app/helpers/maps_helper.rb
module MapsHelper

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=300x300&zoom=17"
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/checkins/_form.html.erb
<%= form_for @checkin, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @checkin.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h4>

      <ul>
      <% @checkin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
      <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
      <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
      <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, class: "col-sm-2 control-label" %>
      <%= f.text_field :user_id, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<div class="page-header">
  <%= link_to checkins_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @checkin, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing checkin</h1>
</div>

<%= render 'form' %>

app/views/checkins/index.html.erb
<% if current_page?(root_path)%>
<div class="jumbotronTransp">
  <div class="row">
    <div class="col-md-9">
      <h1>Cowork Fargo</h1>
    </div>

    <div class="col-md-3 ">
      <%= link_to "Join the community!", signup_path, class: "btn btn-primary btn-block btn-lg"%>
    </div>
  </div>
  <h3>Connecting remote workers and students in the
    Fargo, Moorhead, West Fargo area.</h3>
</div>
<div class="container-static">
<% end%>

<div class="row checkins">
  <div class="col-md-7">
    <div id="map" style='width: 100%; height: 600px;'></div>
  </div>

  <div class="col-md-5">

    <%= link_to new_checkin_path do %>
      <button class="btn btn-warning">Add Your Coworking Location</button>
    <% end %>

    <hr>

    <table>

    <% @checkins.each do |checkin| %>

      <tr>
        <h3> <%= gravatar_for(checkin.user, size: 50 )%>
          <%= checkin.name %>
        </h3>
        <h4><%= checkin.user.name %></h4>

        <p><%= checkin.address %></p>

        <p><%= checkin.description %></p>
      </tr>
    <% end %>
  </table>


  </div>

</div>
<% if current_page?(root_path)%>
</div>
<% end %>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    $(document).on('ready', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/checkins/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>New checkin</h2>

    </div>




</div>

<%= render 'form' %>
</div>

app/views/checkins/show.html.erb
<div class="row">
    <div class="col-md-6 map_box">
      <%= static_map_for(@checkin) %>
    </div>

  <div class="col-md-6">
      <h2><%= @checkin.name %></h2>
      <p><%= @checkin.address %></p>
      <p><%= @checkin.description %></p>

      <%= link_to "Edit", edit_checkin_path(@checkin), class: "btn btn-primary" %>
      <%= link_to "Back", checkins_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/_defaults.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Bungee+Shade', media: 'all', 'data-turbolinks-track' => true %>
<%= favicon_link_tag 'favicon.ico' %>

<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
<link rel="icon" href="favicon.ico" type="image/x-icon">

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2016 <%= link_to("Kailee Gray", "https://github.com/kaileeagray/", target:"_blank", rel:"noopener no referrer")%>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%unless current_page?(root_path)%>
      <%= link_to "Cowork Fargo", root_path, id: "logo" %>
    <%end%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Checkin", new_checkin_path%></li>
        <li><%= link_to "Coworkers", users_path%></li>
        <li><%= link_to "Live Coworkers", map_path%></li>
        <!-- <li><%= link_to "Sign Up", signup_path%></li>
        <li><%= link_to "Log In", '#'%></li> -->
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<div class="row flash">
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
</div>

app/views/layouts/_rails_defaults.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Bungee+Shade', media: 'all', 'data-turbolinks-track' => true %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= render 'layouts/defaults' %>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <% if current_page?(root_path)%>
        <%= yield %>
      <% else %>
      <div class="container-static">
        <%= yield %>
      </div>
      <% end %>
      <%= render 'layouts/footer' %>
    </div>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyDZhxMwZ3CNfILJ4sX3Ou__dk0cdfiMBto" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag "application" %>

    <%= yield(:after_js) %>
  </body>

</html>

app/views/maps/_map.html.erb
<div id="map-container">
  <div id="map-canvas">
    <div id="map" style='width: 100%; height: 600px;'></div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    $(document).on('ready', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/maps/_map_box.html.erb
<div class="map_box">
  <h3><%= checkin.name %></h3>
  <p><%= checkin.address %></p>
  <%= link_to "Details", checkin_path(checkin), target: :blank, class: "btn btn-warning" %>
</div>

app/views/maps/show.html.erb
<% provide(:title, "Join a Coworker") %>

<%= render 'map'%>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<h3>
  <%= link_to("Code", "https://github.com/kaileeagray/cowork-fargo", target:"_blank", rel:"noopener no referrer")%>
  created for <%= link_to("Hack Fargo", "http://hackfargo.co/", target:"_blank", rel:"noopener no referrer")%>.
</h3>
<h3>Check out <%=link_to("The Prairie Den", "https://theprairieden.com/", target:"_blank", rel:"noopener no referrer") %> for  24/7 coworking in the Fargo area. </h3>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div id="contact">
  <table>

  <h1 >Contact</h1>
      <tr>
    <td>
      <%= link_to "https://www.linkedin.com/in/kailee-gray-77337833", target:"_blank", rel:"noopener no referrer" do %>
        <%= image_tag 'linkedin.png' %>
      <% end %>
      </td>
      <td>
        <%= link_to "http://www.facebook.com/kailee.gray", target:"_blank", rel:"noopener no referrer" do %>
          <%= image_tag 'facebook.png' %>
        <% end %>
      </td>
      <td>
        <%= link_to "http://www.twitter.com/kaileeagray", target:"_blank", rel:"noopener no referrer" do %>
          <%= image_tag 'twitter.png' %>
        <% end %>
      </td>
      <td>
        <%= link_to "https://learn.co/kaileeagray", target:"_blank", rel:"noopener no referrer" do %>
          <%= image_tag 'learn.png' %>
        <% end %>
    </td>
    <td>
        <%= link_to "http://freecodecamp.com/kaileeagray", target:"_blank", rel:"noopener no referrer" do %>
          <%= image_tag 'fcc.png' %>
        <% end %>
    </td>
  </tr>

</table>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>


  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<h2> <%= gravatar_for user %>
  <%= user.name %>
</h2>

<p>
</p>

app/views/users/index.html.erb
<% provide(:title, 'All Coworkers') %>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Join') %>
<% provide(:button_text, 'Create My Account') %>


<h2>Join our community!</h2>
  <%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>

<%= render @user %>